CREATE TABLE ILANDER(
    ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    TOKEN_COUNT INT NOT NULL DEFAULT 0,
    LAST_CONNEXION BIGINT,
    LAST_NEWS_PULL BIGINT
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    expires_at TIMESTAMPTZ NOT NULL
);
