// AUTOGENERATED Components module
pub mod button;
pub mod card;
pub mod avatar;
pub mod badge;
pub mod toast;
pub mod textarea;
pub mod input;
pub mod form;
pub mod label;
pub mod navbar;
pub mod drag_and_drop_list;
pub mod select;
pub mod date_picker;
pub mod popover;
pub mod calendar;
